import{S as c,i as l}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();let a=new c(".gallery li a");a.on("show.simplelightbox",function(){});a.on("error.simplelightbox",function(t){console.log(t)});function d(t){console.log(t),l.show({title:"",icon:"icon-person",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function u(t,s){console.log(t);const r=t.hits.map(i=>`<li>
                <a href="${i.largeImageURL}"><img src='${i.webformatURL}' alt='${i.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${i.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${i.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${i.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${i.downloads}</p></div>
                </div>
            </li>`).join("");s.textContent="",s.insertAdjacentHTML("beforeend",r),a.refresh()}function f(t,s){fetch(`https://pixabay.com/api/?${t}`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>u(r,s)).catch(r=>d(r))}const m=document.querySelector("form"),h=document.querySelector(".photo-list");let p=new URLSearchParams({key:"7706316-da1567048322714709989c4f8",q:"blue+car",lang:"en",id:"",image_type:"all",orientation:"horizontal",category:"",min_width:"0",min_height:"0",colors:"",editors_choice:!1,safesearch:!0,order:"popular",page:1,per_page:10,callback:"",pretty:!1});m.addEventListener("submit",t=>{console.log(t.target),t.preventDefault(),f(p,h)});
//# sourceMappingURL=commonHelpers.js.map
