import{S as u,i as m}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const n of i.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function e(t){if(t.ep)return;t.ep=!0;const i=s(t);fetch(t.href,i)}})();const h=new u(".gallery li a");function c(o,r){let s;switch(o.toLowerCase()){case"error":s="red";break;case"info":s="blue";break;case"success":s="green";break}m.show({title:`${o}`,color:s,position:"topRight",message:`${r}`})}function f(o,r){console.log(o);const s=o.hits.map(e=>`<li>
                <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
                </div>
            </li>`).join("");r.textContent="",r.insertAdjacentHTML("beforeend",s),h.refresh()}class d{constructor(){this.element=document.querySelector(".js-loader-text"),this.options={text:"Loading images, please wait",loader:".",count:3}}createInterval({count:r,text:s,loader:e}){console.log("New interval"),console.log(this),this.element.classList.remove("js-hidden");let t=0;this.interval=setInterval(()=>{t>r&&(t=0),this.element.innerText=s.padEnd(s.length+t,e),t++},200)}removeInterval(r){console.log("Interval cleared",r),clearInterval(r),this.element.classList.add("js-hidden")}init(){this.element.classList.add("js-hidden")}}function p(o,r){const s=new d;s.createInterval(s.options),setTimeout(()=>{fetch(`https://pixabay.com/api/?${o}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(!e.hits||e.hits.length===0)throw new Error("Error! Nothing to load");f(e,r)}).catch(e=>{console.log(e),c("Error","Sorry, there are no images matching your search query. Please try again!")}).finally(()=>s.removeInterval(s.interval))},2e3)}const a=document.querySelector("form"),g=document.querySelector(".photo-list"),v=new d;v.init();let l=new URLSearchParams({key:"7706316-da1567048322714709989c4f8",q:"",lang:"en",id:"",image_type:"photo",orientation:"horizontal",category:"",min_width:"0",min_height:"0",colors:"",editors_choice:!1,safesearch:!1,order:"popular",page:1,per_page:10,callback:"",pretty:!1});a.addEventListener("submit",o=>{if(o.preventDefault(),!a.elements[0].value.trim()){c("Info","Search input must be filled!");return}l.set("q",a.elements[0].value),p(l,g)});
//# sourceMappingURL=commonHelpers.js.map
