import{S as u,i as m}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const h="/goit-js-hw-11/assets/info-28eb2f9b.svg",f="/goit-js-hw-11/assets/icon-error-9681c3d4.svg",g={info:h,error:f},p=new u(".gallery li a");function l(i,s){let r;switch(i.toLowerCase()){case"error":r="red";break;case"info":r="blue";break;case"success":r="green";break}m.show({title:`${i}`,color:r,maxWidth:"33%",iconUrl:g[i.toLowerCase()],position:"topRight",message:`${s}`})}function v(i,s){console.log(i);const r=i.hits.map(e=>`<li>
                <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
                </div>
            </li>`).join("");s.textContent="",s.insertAdjacentHTML("beforeend",r),p.refresh()}class d{constructor(){this.element=document.querySelector(".js-loader-text"),this.options={text:"Loading images, please wait",loader:".",count:3}}createInterval({count:s,text:r,loader:e}){this.element.classList.remove("js-hidden");let t=0;this.interval=setInterval(()=>{t>s&&(t=0),this.element.innerText=r.padEnd(r.length+t,e),t++},200)}removeInterval(s){clearInterval(s),this.element.classList.add("js-hidden")}init(){this.element.classList.add("js-hidden")}}function y(i,s){const r=new d;r.createInterval(r.options),fetch(`https://pixabay.com/api/?${i}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(!e.hits||e.hits.length===0)throw new Error("Error! Nothing to load");v(e,s)}).catch(e=>{l("Error","Sorry, there are no images matching your search query. Please try again!")}).finally(()=>r.removeInterval(r.interval))}const a=document.querySelector("form"),L=document.querySelector(".photo-list"),w=new d;w.init();let c=new URLSearchParams({key:"7706316-da1567048322714709989c4f8",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0});a.addEventListener("submit",i=>{if(i.preventDefault(),!a.elements[0].value.trim()){l("Info","Search input must be filled!");return}c.set("q",a.elements[0].value),y(c,L)});
//# sourceMappingURL=commonHelpers.js.map
